### ISSUE TITLE
Giraffe is missing (p. 16)

### ISSUE THREAD

**Issue by dohliam** [marvindanig/ABCD-Animal-Book#1]
The giraffe on page 16 is missing -- in fact [body.html](https://github.com/marvindanig/ABCD-Animal-Book/blob/master/manuscript/page-16/body.html) is a blank file. However, in the bubbl.in version of the book, the giraffe is present.

**Comment by marvindanig** [comment]
Added. A few more content updates are likely because the book precedes the framework it was later remade with.

**Comment by judag** [comment]
I wiil check and fix this and add all the updates!!! :) Thanks for your advice!!!

**Comment by judag** [comment]
Hi !!!
I don´t know what happened with the girafe because I did not make any change on it... I will check this and make the updates from the others animals...:)
Cheers!!! :)
Judith

Date: Sat, 12 Mar 2016 09:48:30 -0800

**Comment by marvindanig** [comment]
@judag I've fixed it and closed the issue. Thanks!
